version: "3"
services:
  qrcodeapp:
    restart: "always"
    build: ./back-end
    ports:
      - "8012:3000"
    volumes:
      - "./back-end/html:/html:rw"
    environment:
      PORT: "3000"
    networks:
      - "mmfei_network_frontend"
      - "mmfei_network_backend"
networks:
  mmfei_network_frontend:
    external:
      name: openresty_dockerfile_mmfei_network_backend
  mmfei_network_backend:
    external:
      name: openresty_dockerfile_mmfei_network_frontend
